language: java
jdk:
  - openjdk7

branches:
  only:
    - deploy-snapshot

env:
  global:
    - secure: "gey7ZBlMVYn8ZKDh4m8q6YbeFKS63vObq8AWJ9rGJmpFAteKMDymPPHjvRJoShw+8MvhR47zkRMI7PkM1gRHnl8uSYHDiz5yS2th2Ds/6U+83nDJ77yCy2P5vgiwqkEf6T6YwLhHWF8EfRZ5ekHejt5ELoGFMNMT1wwukEL3zCg="
    - secure: "Tz5G74aAHUMmwD7FHWi02d+kIwDoIgL3DSWbPJnnJtK7H+y07n0JrPWl4O6HRhfNrB9LyOEIgD6I7kQSXac4RCl+6eT+Yx2V36NWS/U2fC8ZCPn0eyp8WmSS46bWIhCF+xCdDMa3wUpPwKIyZuE6+UK1AOvvEBZF3HM85lsbtac="

install:
  mvn install -DskipTests=true -Dgpg.skip=true

script:
  mvn deploy -Dgpg.skip=true

